Add typedef
aliyun/darabonba pull request #115
Opened 2022-05-11 13:25 UTC by peze

2022-05-12 02:28 UTC, yndu13 approved these changes

2022-05-12 02:31 UTC, JacksonTian commented on lib/parser.js
> +    if (this.look.tag === ';') {
分号可省略么。

2022-05-12 02:33 UTC, JacksonTian commented on lib/semantic.js
> +        this.error(`redefined type "${key}"`, node.value);
redefined typedef

2022-05-12 02:34 UTC, JacksonTian commented on package.json
> +  "version": "1.3.8",
版本号在发版的时候改。

2022-05-12 02:35 UTC, JacksonTian commented on lib/parser.js
> +    if (this.look.tag === ';') {
建议强制分号。

2022-05-12 02:35 UTC, JacksonTian requested changes
报错消息那里需要改正一下

2022-05-13 03:14 UTC, JacksonTian approved these changes

2022-05-13 03:14 UTC, merged